query AppProduct($slug: String!, $locale: String) {
  appProduct(slug: $slug, locale: $locale) {
    id
    name
    slug
    vendor
    version
    icon
    linkText
    title
    categories
    categoryId 
    fullDescription
    installationSteps
    screenshots
    registry
    terms
    permissions {
      name
      description
    }
    billing {
      deactivationRoute
      termsURL
      free
      policies {
        currency
        billing {
          taxClassification
          items {
            itemCurrency
            fixed
            calculatedByMetricUnit {
              metricId
              metricName
              minChargeValue
              route
              ranges {
                exclusiveFrom
                inclusiveTo
                multiplier
              }
            }
          }
        }
      }
    }
  }
}
