query AppProduct($slug: String!) {
  appProduct(slug: $slug) {
    id
    name
    slug
    vendor
    version
    icon
    linkText
    title
    categories
    categoryId 
    fullDescription {
      en
      pt
      es
    }
    installationSteps {
      en
      pt
      es
    }
    screenshots {
      en
      pt
      es
    }
    registry
    terms {
      en
      pt
      es
    }
    permissions {
      name
      description
    }
    billing {
      deactivationRoute
      termsURL
      free
      policies {
        currency
        billing {
          taxClassification
          items {
            itemCurrency
            fixed
            calculatedByMetricUnit {
              metricId
              metricName
              minChargeValue
              route
              ranges {
                exclusiveFrom
                inclusiveTo
                multiplier
              }
            }
          }
        }
      }
    }
  }
}
