query AppProduct($slug: String!) {
  appProduct(slug: $slug) {
    id
    name
    slug
    vendor
    version
    icon
    linkText
    title
    categories
    fullDescription
    installationSteps
    registry
    terms
    permissions {
      name
      description
    }
  }
}
