query AvailableApp($id: String!, $skip: Boolean!) {
  availableApp(id: $id) @skip(if: $skip) {
    id
    name
    slug
    vendor
    version
    icon
    title
    categories
    fullDescription
    installationSteps
    registry
    terms
    permissions {
      name
      description
    }
  }
}
